-- Migration: Create Migration Logs Table
-- Description: Creates a table to track applied migrations
-- Version: 20250510000003

-- Create migration_logs table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.migration_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_name TEXT UNIQUE NOT NULL,
  description TEXT,
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add comment to table
COMMENT ON TABLE public.migration_logs IS 'Tracks applied database migrations for audit and troubleshooting purposes';

-- Insert this migration into the table
INSERT INTO public.migration_logs (migration_name, description, applied_at)
VALUES (
  '20250510000003_create_migration_logs',
  'Created migration_logs table',
  NOW()
)
ON CONFLICT (migration_name) DO NOTHING; 